/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'abraithwaite' at '07/07/15 08:45' with Gradle 2.4
 *
 * @author abraithwaite, @date 07/07/15 08:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
